# Generated by Django 3.0.8 on 2020-07-07 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20200707_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-amount',)},
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 21, 13, 2, 56, 381161)),
        ),
    ]
