# Generated by Django 3.0.8 on 2020-07-07 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20200707_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('budget', 'name')},
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 21, 13, 38, 57, 36743)),
        ),
    ]
