# Generated by Django 3.0.8 on 2020-07-07 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20200707_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('due_date', 'name')},
        ),
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 21, 15, 13, 54, 356611)),
        ),
    ]
